language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
#  - ./gradlew build

notifications:
  email:
    recipients:
      -oza.s@husky.neu.edu
      -jain.vars@husky.neu.edu
      -zaveri.v@husky.neu.edu
